CAtegory Controller adding
Furqat-Abduvosiqov/SampleOfEfCore pull request #6
Opened 2023-08-04 14:10 UTC by SamandarHijiakbarovich

2023-08-04 14:53 UTC, Furqat-DevDo requested changes

2023-08-04 14:53 UTC, Furqat-DevDo commented on Models/Requests/CreateCategoryRequest.cs
> +        public Category? Upper { get; set; }
Nima keragi bor ?

2023-08-04 14:53 UTC, Furqat-DevDo commented on Models/Requests/CreateCategoryRequest.cs
> +        public Guid? ImageID { get; set; }
ImageId bo'ladi ID emas

2023-08-04 14:53 UTC, Furqat-DevDo commented on Models/Requests/UpdateCategoryRequest.cs
> +        public Category? Upper { get; set; }
Birxil xato

2023-08-04 14:53 UTC, Furqat-DevDo commented on Models/Responses/GetCategoryResponse.cs
> +            Upper = entitie.Upper;
Negaaaaaaaaaaa?

2023-08-04 14:53 UTC, Furqat-DevDo commented on Services/CategoryService.cs
> +                //ImageId= (Guid?)categoryRequest.ImageId,
Nima bu ??

2023-08-04 14:53 UTC, Furqat-DevDo commented on Services/CategoryService.cs
> +            return categories.Select(x => new GetCategoryResponse(x)).ToList();
Empty Listga tekshiring

2023-08-04 14:53 UTC, Furqat-DevDo commented on Services/CategoryService.cs
> +            return category == null ? null : new GetCategoryResponse(category);
Is null ishlating == emas

2023-08-04 14:53 UTC, Furqat-DevDo commented on Controllers/CategorysController.cs
> +
Documentatsiya qani ????????

2023-08-04 14:53 UTC, Furqat-DevDo commented on Controllers/CategorysController.cs
> +        private readonly ICategoryService categoryService;
_categorService =

2023-08-08 06:39 UTC, SamandarHijiakbarovich commented on Models/Requests/CreateCategoryRequest.cs
> +        public Guid? ImageID { get; set; }
> ImageId bo'ladi ID emas

ImageId ku ustoz Id yozmaganmanku

2023-08-08 06:54 UTC, closed without merging